# Generated by Django 4.1.4 on 2022-12-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hhh',
            new_name='HelloWorld',
        ),
    ]
