"""
Django settings for FinalProjectSite project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy

# django environ
import environ
import os

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# settings.py 가 있는 폴더 위에위에를 베이스 디렉토리로 하겠다.


# READING .env FILE
# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


#ㅅTEMPLATE DIR
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY=env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions', # 지우라는디 어케 지움... 무섭게시리... 
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'playground',
    'debug_toolbar',
    'single_pages',
    'accountapp',
    
    'django.contrib.sites',
    'django.contrib.flatpages',
    'bootstrap4',

    'profileapp',
    'articleapp',

]

SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

ROOT_URLCONF = 'FinalProjectSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # TemplateDoesNotExist 해결
        # 위에서 templates dir지정해주고 내려오기
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FinalProjectSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# STATIC!!!! 어쩌라는겨
STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# os 모듈의 path 함수사용. join : 합친다.

# python manage.py collecstatic : 퍼져있는 Static file 모아주는 명령어


# 앱에 종속되지 않은 static 파일 디렉토리 따로 지정
STATICFILES_DIRS = [
    BASE_DIR/"static",

]


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# next 없이 바로 로그인 창으로 갔을때 아직 page not hound 뜨는거 해결
LOGIN_REDIRECT_URL = reverse_lazy('accountapp:hhhu')
LOGOUT_REDIRECT_URL = reverse_lazy('accountapp:login')


MEDIA_URL = "/media/"
# 미디어 유알엘 : 주소창에 미디어 이하의 경로로 접근을 해야지 실제 미디어 파일에 접근 가능하다

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 미디어 루트 : 미디어 파일을 서버에 올렸을 때 어느 경로에 지정이 될것인지, 그 경로의 루트